revoke all on table public."Admin" from anon, authenticated;
revoke all on table public."Answer" from anon, authenticated;
revoke all on table public."Balance" from anon, authenticated;
revoke all on table public."FreeForm" from anon, authenticated;
revoke all on table public."Information" from anon, authenticated;
revoke all on table public."Links" from anon, authenticated;
revoke all on table public."Ownership" from anon, authenticated;
revoke all on table public."PaidList" from anon, authenticated;
revoke all on table public."Payment" from anon, authenticated;
revoke all on table public."Profile" from anon, authenticated;
revoke all on table public."Questioner" from anon, authenticated;
revoke all on table public."Score" from anon, authenticated;
revoke all on table public."Transaction" from anon, authenticated;
revoke all on table public."Tryout" from anon, authenticated;
revoke all on table public."TryoutList" from anon, authenticated;
revoke all on table public."User" from anon, authenticated;
revoke all on table public._prisma_migrations from anon, authenticated;

alter table public."Admin" enable row level security;
alter table public."Answer" enable row level security;
alter table public."Balance" enable row level security;
alter table public."FreeForm" enable row level security;
alter table public."Information" enable row level security;
alter table public."Links" enable row level security;
alter table public."Ownership" enable row level security;
alter table public."PaidList" enable row level security;
alter table public."Payment" enable row level security;
alter table public."Profile" enable row level security;
alter table public."Questioner" enable row level security;
alter table public."Score" enable row level security;
alter table public."Transaction" enable row level security;
alter table public."Tryout" enable row level security;
alter table public."TryoutList" enable row level security;
alter table public."User" enable row level security;
alter table public._prisma_migrations enable row level security;
